using Erp.Application.Common;

namespace Erp.Api.Endpoints;

internal static class EndpointResults
{
    public static IResult InvalidPagination() => Results.UnprocessableEntity(new
    {
        error = new { code = "INVALID_PAGINATION", message = "页码必须大于0，每页数量必须为1到100" },
    });

    public static IResult From<T>(Result<T> result, Func<T, IResult>? onSuccess = null)
    {
        if (result.IsSuccess && result.Value is not null)
        {
            return onSuccess?.Invoke(result.Value) ?? Results.Ok(result.Value);
        }

        var error = result.Error ?? new ApplicationError("UNKNOWN_ERROR", "请求失败");
        var status = error.Code switch
        {
            "VALIDATION_FAILED" or "FILE_TOO_LARGE" or "FILE_TYPE_NOT_ALLOWED" or "DUPLICATE_CODE" or "DUPLICATE_FACILITY_GROUP" or "DUPLICATE_FACILITY_TYPE" or "DUPLICATE_FACILITY_CODE" or "DUPLICATE_MEMBER_CARD_TYPE" or "DUPLICATE_SUPPLIER_CODE" => StatusCodes.Status422UnprocessableEntity,
            "INVALID_CREDENTIALS" => StatusCodes.Status401Unauthorized,
            "ACCOUNT_LOCKED" => StatusCodes.Status423Locked,
            "FORBIDDEN_ACTION" or "FORBIDDEN_DATA_SCOPE" or "SENSITIVE_EXPORT_FORBIDDEN" or "CANNOT_CHANGE_SELF_AUTHORIZATION" or "CANNOT_RESET_SELF_PASSWORD" => StatusCodes.Status403Forbidden,
            "NOT_FOUND" or "FILE_NOT_FOUND" or "TENANT_NOT_FOUND" or "STORE_NOT_FOUND" or "EMPLOYEE_NOT_FOUND" or "EMPLOYEE_ACCOUNT_NOT_FOUND" or "EMPLOYEE_SHIFT_NOT_FOUND" or "APPOINTMENT_NOT_FOUND" or "SERVICE_ITEM_NOT_FOUND" or "PRODUCT_NOT_FOUND" or "FACILITY_NOT_FOUND" or "FACILITY_SESSION_NOT_FOUND" or "CLEANING_TASK_NOT_FOUND" or "CUSTOMER_NOT_FOUND" or "SERVICE_RECORD_NOT_FOUND" or "MEMBER_CARD_TYPE_NOT_FOUND" or "MEMBER_CARD_NOT_FOUND" or "MEMBER_ACCOUNT_NOT_FOUND" or "MEMBER_TOPUP_NOT_FOUND" or "MEMBER_VERIFICATION_NOT_FOUND" or "SERVICE_PASS_NOT_FOUND" or "SERVICE_PASS_LEDGER_NOT_FOUND" or "POINT_LEDGER_NOT_FOUND" or "SERVICE_ORDER_NOT_FOUND" or "PRODUCT_ORDER_LINE_NOT_FOUND" or "PRICE_BOOK_NOT_FOUND" or "PAYMENT_NOT_FOUND" or "PAYMENT_METHOD_NOT_FOUND" or "SHIFT_NOT_FOUND" or "REFUND_NOT_FOUND" or "REFUND_ALLOCATION_NOT_FOUND" or "CHANNEL_ORDER_NOT_FOUND" or "CHANNEL_REFUND_NOT_FOUND" or "PAYMENT_CHANNEL_NOT_FOUND" or "RECONCILIATION_ITEM_NOT_FOUND" or "SUPPLIER_NOT_FOUND" or "STOCKTAKE_NOT_FOUND" or "INVENTORY_TRANSFER_NOT_FOUND" => StatusCodes.Status404NotFound,
            "VERSION_CONFLICT" or "IDEMPOTENCY_CONFLICT" or "RESOURCE_IN_USE" or "DUPLICATE_TENANT_CODE" or "DUPLICATE_STORE_CODE" or "LAST_STORE_REQUIRED" or "STORE_DISABLE_BLOCKED" or "FACILITY_NOT_AVAILABLE" or "APPOINTMENT_EMPLOYEE_CONFLICT" or "APPOINTMENT_FACILITY_CONFLICT" or "APPOINTMENT_RESOURCE_CONFLICT" or "APPOINTMENT_CREATE_CONFLICT" or "EMPLOYEE_SHIFT_CONFLICT" or "MEMBER_CARD_NOT_ACTIVE" or "MEMBER_VERIFICATION_REQUIRED" or "MEMBER_VERIFICATION_EXPIRED" or "MEMBER_VERIFICATION_NOT_ACTIVE" or "MEMBER_VERIFICATION_MISMATCH" or "SERVICE_PASS_NOT_ACTIVE" or "SERVICE_PASS_NOT_DUE" or "SERVICE_PASS_LEDGER_ALREADY_REVERSED" or "POINT_LEDGER_ALREADY_REVERSED" or "POINTS_NOT_DUE" or "INVALID_STATE_TRANSITION" or "STATE_TRANSITION_NOT_ALLOWED" or "DUPLICATE_CUSTOMER" or "CUSTOMER_MERGE_BLOCKED" or "DUPLICATE_MEMBER_CARD" or "VISIT_ALREADY_HAS_ORDER" or "VISIT_NOT_READY" or "PAYMENT_ALREADY_EXISTS" or "SHIFT_NOT_OPEN" or "SHIFT_ALREADY_OPEN" or "PAYMENT_CHANNEL_NOT_ENABLED" or "CHANNEL_ALREADY_PAID" or "CHANNEL_RESULT_CONFLICT" or "RECONCILIATION_ALREADY_RUNNING" or "INVENTORY_OPENING_ALREADY_POSTED" => StatusCodes.Status409Conflict,
            "PAYMENT_ALLOCATION_UNBALANCED" or "PAYMENT_METHOD_NOT_ALLOWED" or "APPOINTMENT_IN_PAST" or "APPOINTMENT_NOT_STARTED" or "EMPLOYEE_NOT_ELIGIBLE" or "FACILITY_RESERVATION_NOT_ALLOWED" or "MEMBER_CUSTOMER_REQUIRED" or "MEMBER_MOBILE_REQUIRED" or "MEMBER_MOBILE_MISMATCH" or "MEMBER_ACCOUNT_REQUIRED" or "MEMBER_ACCOUNT_TYPE_MISMATCH" or "MEMBER_VERIFICATION_CODE_INVALID" or "INSUFFICIENT_MEMBER_BALANCE" or "INSUFFICIENT_MEMBER_POINTS" or "INSUFFICIENT_SERVICE_PASS_BALANCE" or "SERVICE_PASS_LEDGER_NOT_REVERSIBLE" or "SERVICE_PASS_ORDER_MISMATCH" or "POINT_LEDGER_NOT_REVERSIBLE" or "POINT_REVERSAL_NOT_AVAILABLE" or "REFUND_AMOUNT_EXCEEDED" or "REFUND_ROUTE_UNAVAILABLE" or "REFUND_SOURCE_NOT_SUPPORTED" or "TOPUP_BALANCE_ALREADY_USED" or "TOPUP_BONUS_REVOCATION_MISMATCH" or "INSUFFICIENT_SHIFT_CASH" or "CHANNEL_PAYMENT_REQUIRES_INITIATION" or "CHANNEL_TOPUP_NOT_AVAILABLE" or "CHANNEL_REFUND_MIX_NOT_ALLOWED" or "CHANNEL_REFUND_SOURCE_INVALID" or "PAYMENT_CHANNEL_CREDENTIALS_INCOMPLETE" or "PAYMENT_CHANNEL_ENVIRONMENT_MISMATCH" or "INSUFFICIENT_INVENTORY" or "INVENTORY_RESERVATION_MISMATCH" or "INVENTORY_PRODUCT_NOT_TRACKED" or "INVENTORY_LOT_INSUFFICIENT" or "INVENTORY_TRANSFER_LOT_MISMATCH" or "SUPPLIER_NOT_ACTIVE" or "PRODUCT_INVENTORY_MODE_LOCKED" or "PRODUCT_RETURN_QUANTITY_EXCEEDED" or "SERVICE_EMPLOYEE_REQUIRED" or "SERVICE_EMPLOYEE_NOT_ELIGIBLE" or "COMMISSION_EXCEEDS_LINE_AMOUNT" or "EXPORT_TOO_LARGE" => StatusCodes.Status422UnprocessableEntity,
            "MEMBER_VERIFICATION_RATE_LIMITED" => StatusCodes.Status429TooManyRequests,
            "CHANNEL_INVALID_RESPONSE" or "CHANNEL_SIGNATURE_MISSING" or "CHANNEL_SIGNATURE_INVALID" or "CHANNEL_KEY_MISMATCH" or "CHANNEL_RESPONSE_STALE" or "CHANNEL_REFUND_STATE_UNKNOWN" or "CHANNEL_BILL_INVALID_RESPONSE" or "CHANNEL_BILL_HASH_MISMATCH" or "CHANNEL_BILL_TOO_LARGE" => StatusCodes.Status502BadGateway,
            "VERIFICATION_DELIVERY_UNAVAILABLE" or "FILE_STORAGE_UNAVAILABLE" or "FILE_INTEGRITY_FAILED" or "CHANNEL_UNAVAILABLE" or "CHANNEL_QUERY_FAILED" or "CHANNEL_CLOSE_FAILED" or "CHANNEL_REFUND_UNAVAILABLE" or "CHANNEL_BILL_UNAVAILABLE" or "CHANNEL_BILL_DOWNLOAD_FAILED" => StatusCodes.Status503ServiceUnavailable,
            _ => StatusCodes.Status400BadRequest,
        };

        return Results.Json(new { error, traceId = System.Diagnostics.Activity.Current?.TraceId.ToString() }, statusCode: status);
    }
}
