-- V1 baseline: identity, organization, authorization, catalog, audit and idempotency.
-- PostgreSQL 18.4. All timestamps are UTC timestamptz and all business IDs are app-generated UUIDv7.

CREATE TABLE organization_tenants (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    code varchar(32) NOT NULL,
    name varchar(100) NOT NULL,
    status varchar(24) NOT NULL,
    created_at_utc timestamptz NOT NULL,
    updated_at_utc timestamptz NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_organization_tenants_code UNIQUE (code),
    CONSTRAINT ck_organization_tenants_self CHECK (tenant_id = id),
    CONSTRAINT ck_organization_tenants_status CHECK (status IN ('Enabled', 'Disabled'))
);

CREATE INDEX ix_organization_tenants_tenant_id ON organization_tenants (tenant_id);

CREATE TABLE identity_roles (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES organization_tenants(id),
    name varchar(64),
    normalized_name varchar(64),
    concurrency_stamp text,
    CONSTRAINT uq_identity_roles_tenant_name UNIQUE (tenant_id, normalized_name)
);

CREATE INDEX ix_identity_roles_normalized_name ON identity_roles (normalized_name);

CREATE TABLE identity_users (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES organization_tenants(id),
    display_name varchar(100) NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    created_at_utc timestamptz NOT NULL,
    user_name varchar(100),
    normalized_user_name varchar(100),
    email varchar(256),
    normalized_email varchar(256),
    email_confirmed boolean NOT NULL DEFAULT false,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number varchar(32),
    phone_number_confirmed boolean NOT NULL DEFAULT false,
    two_factor_enabled boolean NOT NULL DEFAULT false,
    lockout_end timestamptz,
    lockout_enabled boolean NOT NULL DEFAULT true,
    access_failed_count integer NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX ix_identity_users_normalized_user_name
    ON identity_users (normalized_user_name)
    WHERE normalized_user_name IS NOT NULL;
CREATE INDEX ix_identity_users_normalized_email ON identity_users (normalized_email);
CREATE INDEX ix_identity_users_tenant_id ON identity_users (tenant_id);

CREATE TABLE identity_role_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id uuid NOT NULL REFERENCES identity_roles(id) ON DELETE CASCADE,
    claim_type text,
    claim_value text
);

CREATE INDEX ix_identity_role_claims_role_id ON identity_role_claims (role_id);

CREATE TABLE identity_user_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES identity_users(id) ON DELETE CASCADE,
    claim_type text,
    claim_value text
);

CREATE INDEX ix_identity_user_claims_user_id ON identity_user_claims (user_id);

CREATE TABLE identity_user_logins (
    login_provider varchar(128) NOT NULL,
    provider_key varchar(128) NOT NULL,
    provider_display_name text,
    user_id uuid NOT NULL REFERENCES identity_users(id) ON DELETE CASCADE,
    PRIMARY KEY (login_provider, provider_key)
);

CREATE INDEX ix_identity_user_logins_user_id ON identity_user_logins (user_id);

CREATE TABLE identity_user_roles (
    user_id uuid NOT NULL REFERENCES identity_users(id) ON DELETE CASCADE,
    role_id uuid NOT NULL REFERENCES identity_roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX ix_identity_user_roles_role_id ON identity_user_roles (role_id);

CREATE TABLE identity_user_tokens (
    user_id uuid NOT NULL REFERENCES identity_users(id) ON DELETE CASCADE,
    login_provider varchar(128) NOT NULL,
    name varchar(128) NOT NULL,
    value text,
    PRIMARY KEY (user_id, login_provider, name)
);

CREATE TABLE organization_stores (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES organization_tenants(id),
    code varchar(32) NOT NULL,
    name varchar(100) NOT NULL,
    time_zone_id varchar(64) NOT NULL,
    status varchar(24) NOT NULL,
    created_at_utc timestamptz NOT NULL,
    updated_at_utc timestamptz NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_organization_stores_tenant_code UNIQUE (tenant_id, code),
    CONSTRAINT ck_organization_stores_status CHECK (status IN ('Enabled', 'Disabled'))
);

CREATE INDEX ix_organization_stores_tenant_id ON organization_stores (tenant_id);

CREATE TABLE organization_user_stores (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES organization_tenants(id),
    user_id uuid NOT NULL REFERENCES identity_users(id),
    store_id uuid NOT NULL REFERENCES organization_stores(id),
    is_default boolean NOT NULL DEFAULT false,
    created_at_utc timestamptz NOT NULL,
    updated_at_utc timestamptz NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_organization_user_stores UNIQUE (user_id, store_id)
);

CREATE INDEX ix_organization_user_stores_tenant_id ON organization_user_stores (tenant_id);
CREATE INDEX ix_organization_user_stores_store_id ON organization_user_stores (store_id);

CREATE TABLE authorization_role_permissions (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES organization_tenants(id),
    role_id uuid NOT NULL REFERENCES identity_roles(id),
    action varchar(128) NOT NULL,
    created_at_utc timestamptz NOT NULL,
    updated_at_utc timestamptz NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_authorization_role_permissions UNIQUE (role_id, action)
);

CREATE INDEX ix_authorization_role_permissions_tenant_id ON authorization_role_permissions (tenant_id);

CREATE TABLE catalog_service_items (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES organization_tenants(id),
    code varchar(40) NOT NULL,
    name varchar(120) NOT NULL,
    standard_duration_minutes integer NOT NULL DEFAULT 0,
    status varchar(24) NOT NULL,
    created_at_utc timestamptz NOT NULL,
    updated_at_utc timestamptz NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_catalog_service_items_tenant_code UNIQUE (tenant_id, code),
    CONSTRAINT ck_catalog_service_items_duration CHECK (standard_duration_minutes BETWEEN 0 AND 1440),
    CONSTRAINT ck_catalog_service_items_status CHECK (status IN ('Enabled', 'Disabled'))
);

CREATE INDEX ix_catalog_service_items_tenant_id ON catalog_service_items (tenant_id);

CREATE TABLE catalog_price_books (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES organization_tenants(id),
    name varchar(120) NOT NULL,
    revision integer NOT NULL DEFAULT 1,
    effective_from date NOT NULL,
    status varchar(24) NOT NULL,
    published_at_utc timestamptz,
    created_at_utc timestamptz NOT NULL,
    updated_at_utc timestamptz NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_catalog_price_books_status CHECK (status IN ('Draft', 'Published', 'Retired'))
);

CREATE INDEX ix_catalog_price_books_tenant_id ON catalog_price_books (tenant_id);
CREATE INDEX ix_catalog_price_books_effective ON catalog_price_books (tenant_id, status, effective_from DESC);

CREATE TABLE catalog_price_book_lines (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES organization_tenants(id),
    price_book_id uuid NOT NULL REFERENCES catalog_price_books(id) ON DELETE CASCADE,
    service_item_id uuid NOT NULL REFERENCES catalog_service_items(id),
    unit_price_minor bigint NOT NULL,
    created_at_utc timestamptz NOT NULL,
    updated_at_utc timestamptz NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_catalog_price_book_lines UNIQUE (price_book_id, service_item_id),
    CONSTRAINT ck_catalog_price_book_lines_price CHECK (unit_price_minor >= 0)
);

CREATE INDEX ix_catalog_price_book_lines_tenant_id ON catalog_price_book_lines (tenant_id);
CREATE INDEX ix_catalog_price_book_lines_service_item ON catalog_price_book_lines (service_item_id);

CREATE TABLE audit_events (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES organization_tenants(id),
    store_id uuid REFERENCES organization_stores(id),
    operator_id uuid REFERENCES identity_users(id),
    action varchar(128) NOT NULL,
    entity_type varchar(80) NOT NULL,
    entity_id uuid,
    previous_state varchar(40),
    current_state varchar(40),
    reason varchar(500),
    trace_id varchar(64) NOT NULL,
    request_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at_utc timestamptz NOT NULL
);

CREATE INDEX ix_audit_events_tenant_time ON audit_events (tenant_id, occurred_at_utc DESC);
CREATE INDEX ix_audit_events_entity ON audit_events (entity_type, entity_id);

CREATE TABLE idempotency_commands (
    command_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES organization_tenants(id),
    operator_id uuid NOT NULL REFERENCES identity_users(id),
    request_hash bytea NOT NULL,
    response_status integer,
    response_body jsonb,
    created_at_utc timestamptz NOT NULL,
    completed_at_utc timestamptz
);

CREATE INDEX ix_idempotency_commands_tenant_created ON idempotency_commands (tenant_id, created_at_utc DESC);

