FROM node:20.17.0 AS build
WORKDIR /app
COPY erp-web/package*.json ./
RUN npm install
COPY erp-web/ .
RUN npm run build

FROM nginx:1.25-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/ /usr/share/nginx/html/
