using Erp.Domain.Common;

namespace Erp.Domain.Customers;

/// <summary>
/// A brand-scoped classification for customer service records. The immutable code is generated by the
/// system; the display name and order are maintained by the brand.
/// </summary>
public sealed class ServiceRecordCategory : Entity
{
    private ServiceRecordCategory()
    {
    }

    public ServiceRecordCategory(Guid tenantId, string code, string name, int sortOrder = 0)
        : base(tenantId)
    {
        Code = Normalize(code, 40, "服务记录分类编码");
        Name = Normalize(name, 60, "服务记录分类名称");
        SetSortOrder(sortOrder);
        Status = ServiceRecordCategoryStatus.Enabled;
    }

    public string Code { get; private set; } = string.Empty;
    public string Name { get; private set; } = string.Empty;
    public int SortOrder { get; private set; }
    public ServiceRecordCategoryStatus Status { get; private set; }

    public void Update(string name, int sortOrder)
    {
        Name = Normalize(name, 60, "服务记录分类名称");
        SetSortOrder(sortOrder);
        Touch();
    }

    public void Enable()
    {
        Status = ServiceRecordCategoryStatus.Enabled;
        Touch();
    }

    public void Disable()
    {
        Status = ServiceRecordCategoryStatus.Disabled;
        Touch();
    }

    private void SetSortOrder(int sortOrder)
    {
        if (sortOrder is < 0 or > 9999)
            throw new DomainRuleException("VALIDATION_FAILED", "分类排序必须在0到9999之间");
        SortOrder = sortOrder;
    }

    private static string Normalize(string value, int maxLength, string displayName)
    {
        var normalized = value.Trim();
        if (normalized.Length is < 1 || normalized.Length > maxLength)
            throw new DomainRuleException("VALIDATION_FAILED", $"{displayName}长度必须为1到{maxLength}个字符");
        return normalized;
    }
}

public enum ServiceRecordCategoryStatus
{
    Enabled = 1,
    Disabled = 2,
}
