import { GiftOutlined, PlusOutlined, UndoOutlined } from "@ant-design/icons";
import { Alert, Button, Card, Empty, Form, Input, InputNumber, Modal, Select, Space, Tag, Typography, message } from "antd";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { apiRequest, ApiError } from "../api/client";
import type { MemberCard, MemberPointSummary, MembershipBenefits, ServiceItem, ServicePass } from "../api/types";
import { useAuth } from "../auth/useAuth";
import { isServicePassDue } from "./membershipRules";

interface IssuePassValues { cardId: string; serviceItemId: string; passName: string; purchasedUses: number; bonusUses: number; validFrom: string; validTo?: string; reason: string }
interface RedeemPassValues { uses: number; serviceOrderId?: string; reason: string }
interface PointValues { cardId: string; units: number; credit: boolean; expiresOn?: string; reason: string }
interface ReasonValues { reason: string }

function commandId() { return crypto.randomUUID() }
function requestError(error: unknown) { return error instanceof ApiError ? error.message : "操作失败，请稍后重试" }

export function MembershipBenefitsSection({ storeId, customerId, cards }: { storeId: string; customerId: string; cards: MemberCard[] }) {
  const auth = useAuth(); const queryClient = useQueryClient()
  const canManage = auth.user?.roles.some((role) => role === "OWNER" || role === "STORE_MANAGER") ?? false
  const canRedeem = auth.user?.roles.some((role) => role === "OWNER" || role === "STORE_MANAGER" || role === "CASHIER") ?? false
  const isOwner = auth.user?.roles.includes("OWNER") ?? false
  const [issueOpen, setIssueOpen] = useState(false); const [pointOpen, setPointOpen] = useState(false)
  const [redeemPass, setRedeemPass] = useState<ServicePass>(); const [reversePass, setReversePass] = useState<{ pass: ServicePass; ledgerId: string }>()
  const [reversePoints, setReversePoints] = useState<{ account: MemberPointSummary; ledgerId: string }>()
  const [issueForm] = Form.useForm<IssuePassValues>(); const [redeemForm] = Form.useForm<RedeemPassValues>()
  const [pointForm] = Form.useForm<PointValues>(); const [reasonForm] = Form.useForm<ReasonValues>()
  const benefits = useQuery({ queryKey: ["membership-benefits", storeId, customerId], queryFn: () => apiRequest<MembershipBenefits>(`/api/v1/membership-benefits?storeId=${storeId}&customerId=${customerId}`) })
  const services = useQuery({ queryKey: ["service-items", "membership-options"], queryFn: () => apiRequest<ServiceItem[]>("/api/v1/catalog/service-items?status=ENABLED") })
  const refresh = () => Promise.all([queryClient.invalidateQueries({ queryKey: ["membership-benefits", storeId, customerId] }), queryClient.invalidateQueries({ queryKey: ["customer", storeId, customerId] })])
  const success = async (text: string) => { message.success(text); setIssueOpen(false); setPointOpen(false); setRedeemPass(undefined); setReversePass(undefined); setReversePoints(undefined); issueForm.resetFields(); redeemForm.resetFields(); pointForm.resetFields(); reasonForm.resetFields(); await refresh() }
  const issue = useMutation({ mutationFn: (values: IssuePassValues) => apiRequest<ServicePass>("/api/v1/membership-benefits/service-passes", { method: "POST", body: JSON.stringify({ storeId, customerId, ...values, bonusUses: values.bonusUses ?? 0, validTo: values.validTo || null, commandId: commandId() }) }), onSuccess: () => success("次卡已发放并写入权益流水"), onError: (error) => message.error(requestError(error)) })
  const redeem = useMutation({ mutationFn: (values: RedeemPassValues) => apiRequest<ServicePass>(`/api/v1/membership-benefits/service-passes/${redeemPass?.id}/redeem`, { method: "POST", body: JSON.stringify({ storeId, uses: values.uses, serviceOrderId: values.serviceOrderId || null, reason: values.reason, expectedVersion: redeemPass?.version, commandId: commandId() }) }), onSuccess: () => success("次卡已核销"), onError: (error) => message.error(requestError(error)) })
  const reversePassMutation = useMutation({ mutationFn: (values: ReasonValues) => apiRequest<ServicePass>(`/api/v1/membership-benefits/service-passes/${reversePass?.pass.id}/reverse`, { method: "POST", body: JSON.stringify({ storeId, ledgerId: reversePass?.ledgerId, reason: values.reason, expectedVersion: reversePass?.pass.version, commandId: commandId() }) }), onSuccess: () => success("次卡核销已撤销"), onError: (error) => message.error(requestError(error)) })
  const expirePass = useMutation({ mutationFn: (pass: ServicePass) => apiRequest<ServicePass>(`/api/v1/membership-benefits/service-passes/${pass.id}/expire`, { method: "POST", body: JSON.stringify({ storeId, reason: "到期权益批次处理", expectedVersion: pass.version, commandId: commandId() }) }), onSuccess: () => success("到期次卡已处理"), onError: (error) => message.error(requestError(error)) })
  const adjustPoints = useMutation({ mutationFn: (values: PointValues) => apiRequest<MemberPointSummary>("/api/v1/membership-benefits/points/adjust", { method: "POST", body: JSON.stringify({ storeId, customerId, ...values, expiresOn: values.credit && values.expiresOn ? values.expiresOn : null, commandId: commandId() }) }), onSuccess: () => success("积分变动已入账"), onError: (error) => message.error(requestError(error)) })
  const reversePointMutation = useMutation({ mutationFn: (values: ReasonValues) => apiRequest<MemberPointSummary>("/api/v1/membership-benefits/points/reverse", { method: "POST", body: JSON.stringify({ storeId, cardId: reversePoints?.account.cardId, ledgerId: reversePoints?.ledgerId, reason: values.reason, commandId: commandId() }) }), onSuccess: () => success("积分扣减已撤销"), onError: (error) => message.error(requestError(error)) })
  const expirePoints = useMutation({ mutationFn: (account: MemberPointSummary) => apiRequest<MemberPointSummary>("/api/v1/membership-benefits/points/expire", { method: "POST", body: JSON.stringify({ storeId, cardId: account.cardId, reason: "到期积分批次处理", commandId: commandId() }) }), onSuccess: () => success("到期积分已处理"), onError: (error) => message.error(requestError(error)) })
  const pointCredit = Form.useWatch("credit", pointForm)
  const today = new Date().toISOString().slice(0, 10)

  return <div>
    <div className="section-heading"><Typography.Title level={4}>次卡与积分</Typography.Title><Space wrap>{canManage && <><Button size="small" icon={<GiftOutlined />} onClick={() => { issueForm.setFieldsValue({ purchasedUses: 1, bonusUses: 0, validFrom: today }); setIssueOpen(true) }}>发放次卡</Button><Button size="small" icon={<PlusOutlined />} onClick={() => { pointForm.setFieldsValue({ credit: true }); setPointOpen(true) }}>积分增减</Button></>}</Space></div>
    <Alert type="info" showIcon title="次卡购买次数先于赠送次数核销；积分按最早到期批次优先使用。所有变动只追加流水，不能直接修改余额。" />
    {benefits.error && <Alert type="error" showIcon title={requestError(benefits.error)} />}
    {!benefits.data?.servicePasses.length ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无次卡" /> : <Space direction="vertical" className="full-width" size="small">{benefits.data.servicePasses.map((pass) => {
      const reversed = new Set(pass.ledgers.filter((line) => line.action === "Reverse").map((line) => line.reversedLedgerId))
      const reversible = pass.ledgers.find((line) => line.action === "Redeem" && !reversed.has(line.id))
      const due = isServicePassDue(pass.status, pass.validTo, today)
      return <Card key={pass.id} size="small"><div className="member-card-title"><div><strong>{pass.passName}</strong><Typography.Text type="secondary"> · {pass.serviceItemName}</Typography.Text></div><Space><Tag color={pass.status === "Active" ? "green" : "default"}>{pass.status === "Active" ? "有效" : pass.status === "Exhausted" ? "已用完" : pass.status === "Expired" ? "已过期" : "已作废"}</Tag>{canRedeem && pass.status === "Active" && !due && <Button size="small" onClick={() => { redeemForm.setFieldsValue({ uses: 1 }); setRedeemPass(pass) }}>核销</Button>}{isOwner && reversible && <Button size="small" icon={<UndoOutlined />} onClick={() => setReversePass({ pass, ledgerId: reversible.id })}>撤销核销</Button>}{canManage && due && <Button size="small" danger loading={expirePass.isPending} onClick={() => expirePass.mutate(pass)}>过期处理</Button>}</Space></div><Typography.Paragraph>剩余 <strong>{pass.remainingUses}</strong> 次（购买 {pass.remainingPurchasedUses}，赠送 {pass.remainingBonusUses}） · 有效期 {pass.validFrom} 至 {pass.validTo ?? "长期"}</Typography.Paragraph><Space wrap>{pass.ledgers.slice(0, 5).map((line) => <Tag key={line.id}>{line.action} {line.purchasedUsesDelta + line.bonusUsesDelta > 0 ? "+" : ""}{line.purchasedUsesDelta + line.bonusUsesDelta} · {line.reason}</Tag>)}</Space></Card>
    })}</Space>}
    <Typography.Title level={5} style={{ marginTop: 16 }}>积分账户</Typography.Title>
    {!benefits.data?.pointAccounts.length ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无积分账户" /> : <Space direction="vertical" className="full-width" size="small">{benefits.data.pointAccounts.map((account) => {
      const reversed = new Set(account.ledgers.filter((line) => line.businessType === "PointReversal").map((line) => line.businessId))
      const debit = account.ledgers.find((line) => line.businessType === "PointManualDebit" && !reversed.has(line.id))
      return <Card key={account.accountId} size="small"><div className="member-card-title"><strong>{account.balanceUnits} 积分</strong><Space>{canManage && <Button size="small" onClick={() => expirePoints.mutate(account)}>处理到期积分</Button>}{isOwner && debit && <Button size="small" icon={<UndoOutlined />} onClick={() => setReversePoints({ account, ledgerId: debit.id })}>撤销扣减</Button>}</Space></div><Space wrap>{account.grants.map((grant) => <Tag key={grant.id} color={grant.status === "Active" ? "blue" : "default"}>批次剩余 {grant.remainingUnits}/{grant.originalUnits} · {grant.expiresOn ?? "长期"}</Tag>)}</Space></Card>
    })}</Space>}
    <Modal title="发放次卡" open={issueOpen} onCancel={() => setIssueOpen(false)} onOk={() => issueForm.submit()} confirmLoading={issue.isPending} destroyOnHidden><Form<IssuePassValues> form={issueForm} layout="vertical" onFinish={(values) => issue.mutate(values)}><Form.Item name="cardId" label="会员卡" rules={[{ required: true }]}><Select options={cards.map((card) => ({ value: card.id, label: `${card.cardTypeName} · ${card.maskedCardNo}` }))} /></Form.Item><Form.Item name="serviceItemId" label="适用服务项目" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={(services.data ?? []).map((item) => ({ value: item.id, label: item.name }))} /></Form.Item><Form.Item name="passName" label="次卡名称" rules={[{ required: true }, { max: 100 }]}><Input /></Form.Item><Space className="full-width"><Form.Item name="purchasedUses" label="购买次数" rules={[{ required: true }]}><InputNumber min={0} max={100000} precision={0} /></Form.Item><Form.Item name="bonusUses" label="赠送次数" rules={[{ required: true }]}><InputNumber min={0} max={100000} precision={0} /></Form.Item></Space><Form.Item name="validFrom" label="生效日" rules={[{ required: true }]}><Input type="date" /></Form.Item><Form.Item name="validTo" label="到期日（可选）"><Input type="date" /></Form.Item><Form.Item name="reason" label="发放原因" rules={[{ required: true }, { max: 500 }]}><Input.TextArea rows={2} /></Form.Item></Form></Modal>
    <Modal title="次卡核销" open={Boolean(redeemPass)} onCancel={() => setRedeemPass(undefined)} onOk={() => redeemForm.submit()} confirmLoading={redeem.isPending} destroyOnHidden><Form<RedeemPassValues> form={redeemForm} layout="vertical" onFinish={(values) => redeem.mutate(values)}><Alert type="warning" showIcon title="先扣购买次数，再扣赠送次数；设施计时不会自动触发核销。" /><Form.Item name="uses" label="核销次数" rules={[{ required: true }]}><InputNumber min={1} max={redeemPass?.remainingUses} precision={0} className="full-width" /></Form.Item><Form.Item name="serviceOrderId" label="关联消费单ID（可选）"><Input placeholder="关联时服务端会核验顾客和项目" /></Form.Item><Form.Item name="reason" label="核销说明" rules={[{ required: true }, { max: 500 }]}><Input.TextArea rows={2} /></Form.Item></Form></Modal>
    <Modal title="积分增减" open={pointOpen} onCancel={() => setPointOpen(false)} onOk={() => pointForm.submit()} confirmLoading={adjustPoints.isPending} destroyOnHidden><Form<PointValues> form={pointForm} layout="vertical" onFinish={(values) => adjustPoints.mutate(values)}><Form.Item name="cardId" label="会员卡" rules={[{ required: true }]}><Select options={cards.map((card) => ({ value: card.id, label: `${card.cardTypeName} · ${card.maskedCardNo}` }))} /></Form.Item><Form.Item name="credit" label="变动类型" rules={[{ required: true }]}><Select options={[{ value: true, label: "增加积分" }, { value: false, label: "扣减积分" }]} /></Form.Item><Form.Item name="units" label="积分数量" rules={[{ required: true }]}><InputNumber min={1} max={1000000000} precision={0} className="full-width" /></Form.Item>{pointCredit && <Form.Item name="expiresOn" label="到期日（可选）"><Input type="date" min={today} /></Form.Item>}<Form.Item name="reason" label="变动原因" rules={[{ required: true }, { max: 500 }]}><Input.TextArea rows={2} /></Form.Item></Form></Modal>
    <Modal title={reversePass ? "撤销次卡核销" : "撤销积分扣减"} open={Boolean(reversePass || reversePoints)} onCancel={() => { setReversePass(undefined); setReversePoints(undefined) }} onOk={() => reasonForm.submit()} confirmLoading={reversePassMutation.isPending || reversePointMutation.isPending} destroyOnHidden><Form<ReasonValues> form={reasonForm} layout="vertical" onFinish={(values) => reversePass ? reversePassMutation.mutate(values) : reversePointMutation.mutate(values)}><Alert type="warning" showIcon title="撤销会新增一条反向流水，原流水和审计记录仍保留。" /><Form.Item name="reason" label="撤销原因" rules={[{ required: true }, { max: 500 }]}><Input.TextArea rows={3} /></Form.Item></Form></Modal>
  </div>
}
