import { BarChartOutlined, ClockCircleOutlined, ExclamationCircleOutlined, ShopOutlined, WalletOutlined } from '@ant-design/icons'
import { Alert, Card, Col, Empty, Input, Row, Space, Statistic, Table, Tag, Typography } from 'antd'
import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { apiRequest } from '../api/client'
import type { OperationsReport, ServicePerformance } from '../api/types'
import { useAuth } from '../auth/useAuth'

function dateString(date: Date) { const year = date.getFullYear(); const month = String(date.getMonth() + 1).padStart(2, '0'); const day = String(date.getDate()).padStart(2, '0'); return `${year}-${month}-${day}` }
function money(minor: number) { return `¥${(minor / 100).toFixed(2)}` }
function duration(seconds: number) { if (seconds < 60) return `${seconds} 秒`; if (seconds < 3600) return `${(seconds / 60).toFixed(1)} 分钟`; return `${(seconds / 3600).toFixed(1)} 小时` }

export function ReportsPage() {
  const auth = useAuth(); const storeId = auth.store?.id; const today = dateString(new Date()); const weekAgo = new Date(); weekAgo.setDate(weekAgo.getDate() - 6)
  const [fromDate, setFromDate] = useState(dateString(weekAgo)); const [toDate, setToDate] = useState(today)
  const report = useQuery({ queryKey: ['operations-report', storeId, fromDate, toDate], enabled: Boolean(storeId && fromDate && toDate), queryFn: () => apiRequest<OperationsReport>(`/api/v1/reports/operations?storeId=${storeId}&fromDate=${fromDate}&toDate=${toDate}`) })
  const maxDaily = Math.max(1, ...(report.data?.daily.map((row) => row.settledRevenueMinor) ?? []))
  const maxMix = Math.max(1, ...(report.data?.paymentMix.map((row) => row.amountMinor) ?? []))
  const serviceColumns = [
    { title: '服务项目', dataIndex: 'itemName', render: (value: string, record: ServicePerformance) => <div className="audit-action"><strong>{value}</strong><Typography.Text type="secondary">{record.itemCode}</Typography.Text></div> },
    { title: '结算单数', dataIndex: 'orderCount', align: 'right' as const }, { title: '数量', dataIndex: 'quantity', align: 'right' as const },
    { title: '成交金额', dataIndex: 'revenueMinor', align: 'right' as const, render: (value: number) => <strong>{money(value)}</strong> },
  ]
  return <div className="page-stack">
    <div className="page-heading"><div><Typography.Title level={2}>经营报表</Typography.Title><Typography.Paragraph>所有指标来自当前门店业务表；结算、退款、净额和外部待核对分别展示。</Typography.Paragraph></div><Space><Input type="date" value={fromDate} max={toDate} onChange={(event) => setFromDate(event.target.value)} /><span>至</span><Input type="date" value={toDate} min={fromDate} max={today} onChange={(event) => setToDate(event.target.value)} /></Space></div>
    <Alert type="info" showIcon title={`报表口径按门店时区 ${report.data?.timeZoneId ?? '加载中'} 计算；当前单次最多查询 92 天。`} />
    <Row gutter={[16, 16]}><Col span={4}><Card className="report-metric"><Statistic title="业务已结算" value={(report.data?.summary.settledRevenueMinor ?? 0) / 100} precision={2} prefix="¥" /><span>退款前结算总额</span></Card></Col><Col span={4}><Card className="report-metric warning"><Statistic title="已完成退款" value={(report.data?.summary.refundMinor ?? 0) / 100} precision={2} prefix="¥" /><span>按退款完成日冲减</span></Card></Col><Col span={4}><Card className="report-metric"><Statistic title="结算净额" value={(report.data?.summary.netRevenueMinor ?? 0) / 100} precision={2} prefix="¥" /><span>结算减已完成退款</span></Card></Col><Col span={4}><Card className="report-metric"><Statistic title="已记录资金净额" value={(report.data?.summary.recordedFundsMinor ?? 0) / 100} precision={2} prefix={<WalletOutlined />} /><span>允许出现退款净流出</span></Card></Col><Col span={4}><Card className="report-metric warning"><Statistic title="外部待核对" value={(report.data?.summary.pendingReconciliationMinor ?? 0) / 100} precision={2} prefix={<ExclamationCircleOutlined />} /><span>不能视为渠道已确认</span></Card></Col><Col span={4}><Card className="report-metric"><Statistic title="结算客单价" value={(report.data?.summary.averageTicketMinor ?? 0) / 100} precision={2} prefix="¥" /><span>{report.data?.summary.settledOrderCount ?? 0} 张结算单</span></Card></Col></Row>
    <Row gutter={[16, 16]}><Col span={15}><Card variant="borderless" title="每日结算净额走势" extra={<Tag>{report.data?.fromDate} 至 {report.data?.toDate}</Tag>}><div className="daily-chart">{report.data?.daily.map((row) => <div key={row.date} className="daily-column"><div className="daily-value">{money(row.netRevenueMinor)}</div><div className="daily-bars"><span className="bar-pending" style={{ height: `${row.pendingReconciliationMinor <= 0 ? 0 : Math.max(3, row.pendingReconciliationMinor / maxDaily * 150)}px` }} title={`待核对 ${money(row.pendingReconciliationMinor)}`} /><span className="bar-recorded" style={{ height: `${row.recordedFundsMinor <= 0 ? 0 : Math.max(3, row.recordedFundsMinor / maxDaily * 150)}px` }} title={`已记录净额 ${money(row.recordedFundsMinor)}`} /></div><strong>{row.date.slice(5)}</strong><small>退款 {money(row.refundMinor)}</small></div>)}</div><div className="chart-legend"><span><i className="recorded-dot" />已记录资金净额</span><span><i className="pending-dot" />外部待核对</span></div></Card></Col><Col span={9}><Card variant="borderless" title="支付构成"><div className="mix-list">{report.data?.paymentMix.length ? report.data.paymentMix.map((row) => <div key={row.methodCode}><div><strong>{row.methodName}</strong><span>净额 {money(row.netAmountMinor)} · {row.allocationCount} 笔收款</span></div><div className="mix-track"><span style={{ width: `${Math.max(0, row.netAmountMinor) / maxMix * 100}%` }} /></div>{row.refundMinor > 0 && <Tag color="red">退款 {money(row.refundMinor)}</Tag>}{row.pendingReconciliationMinor > 0 && <Tag color="orange">待核对 {money(row.pendingReconciliationMinor)}</Tag>}</div>) : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无支付数据" />}</div></Card></Col></Row>
    <Row gutter={[16, 16]}><Col span={15}><Card variant="borderless" title="服务项目成交排行"><Table<ServicePerformance> rowKey="serviceItemId" columns={serviceColumns} dataSource={report.data?.services} pagination={false} locale={{ emptyText: <Empty description="暂无已结算项目" /> }} /></Card></Col><Col span={9}><Card variant="borderless" title="设施记录占用"><Alert type="warning" showIcon title="仅展示记录时长及其占比，不等于营业时间利用率。" className="report-inline-alert" /><div className="facility-usage-list">{report.data?.facilities.length ? report.data.facilities.map((row) => <div key={row.facilityId}><div><strong><ShopOutlined /> {row.facilityName}</strong><span>{duration(row.activeSeconds)}</span></div><div className="mix-track facility"><span style={{ width: `${row.usageShare * 100}%` }} /></div><small>占全部设施记录时长 {(row.usageShare * 100).toFixed(1)}%</small></div>) : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无设施占用记录" />}</div></Card></Col></Row>
    <Row gutter={[16, 16]}><Col span={8}><Card variant="borderless"><Statistic title="接待次数" value={report.data?.summary.visitCount ?? 0} prefix={<ShopOutlined />} suffix="次" /></Card></Col><Col span={8}><Card variant="borderless"><Statistic title="设施记录占用" value={(report.data?.summary.facilityActiveSeconds ?? 0) / 3600} precision={1} prefix={<ClockCircleOutlined />} suffix="小时" /></Card></Col><Col span={8}><Card variant="borderless"><Statistic title="数据更新" value={report.isFetching ? '刷新中' : '已读取'} prefix={<BarChartOutlined />} /></Card></Col></Row>
  </div>
}
