import { CalendarOutlined, CheckCircleOutlined, EditOutlined, PlusOutlined, StopOutlined, TeamOutlined } from '@ant-design/icons'
import { Alert, Button, Card, Form, Input, Modal, Pagination, Select, Space, Table, Tabs, Tag, Typography, message } from 'antd'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useEffect, useMemo, useState } from 'react'
import { ApiError, apiRequest } from '../api/client'
import type { Appointment, CustomerSummary, EmployeeShift, PageResult, SchedulingResource, ServiceItem } from '../api/types'
import { useAuth } from '../auth/useAuth'
import { useDebouncedValue } from '../hooks/useDebouncedValue'
import { isValidPeriod, toLocalDateTimeValue, toUtcIso } from './schedulingRules'

interface AppointmentValues { customerId: string; serviceItemId: string; employeeId?: string; facilityId?: string; startsAtLocal: string; endsAtLocal: string; note?: string }
interface ShiftValues { employeeId: string; startsAtLocal: string; endsAtLocal: string; note?: string }

const appointmentStatus: Record<string, { label: string; color: string }> = {
  Scheduled: { label: '待到店', color: 'blue' }, Arrived: { label: '已到店', color: 'green' },
  Cancelled: { label: '已取消', color: 'default' }, NoShow: { label: '爽约', color: 'orange' },
}
const shiftStatus: Record<string, { label: string; color: string }> = {
  Scheduled: { label: '已排班', color: 'green' }, Cancelled: { label: '已取消', color: 'default' },
}
function commandId() { return crypto.randomUUID() }
function dateTime(value: string) { return new Date(value).toLocaleString('zh-CN', { hour12: false }) }
function defaultPeriod(minutes = 60) { const start = new Date(Date.now() + 60 * 60_000); start.setMinutes(Math.ceil(start.getMinutes() / 15) * 15, 0, 0); return { startsAtLocal: toLocalDateTimeValue(start), endsAtLocal: toLocalDateTimeValue(new Date(start.getTime() + minutes * 60_000)) } }
function queryRange() { const from = new Date(); from.setHours(0, 0, 0, 0); const to = new Date(from); to.setDate(to.getDate() + 14); return { fromUtc: from.toISOString(), toUtc: to.toISOString() } }

export function SchedulingPage() {
  const auth = useAuth(); const storeId = auth.store?.id; const queryClient = useQueryClient()
  const isManager = auth.user?.roles.some((role) => role === 'OWNER' || role === 'STORE_MANAGER') ?? false
  const canOperate = isManager || (auth.user?.roles.includes('FRONT_DESK') ?? false)
  const [activeTab, setActiveTab] = useState('appointments'); const [query, setQuery] = useState(''); const search = useDebouncedValue(query.trim())
  const [status, setStatus] = useState<string>(); const [appointmentPage, setAppointmentPage] = useState(1); const [shiftPage, setShiftPage] = useState(1)
  const [editingAppointment, setEditingAppointment] = useState<Appointment | 'new'>(); const [editingShift, setEditingShift] = useState<EmployeeShift | 'new'>()
  const [appointmentForm] = Form.useForm<AppointmentValues>(); const [shiftForm] = Form.useForm<ShiftValues>(); const range = useMemo(queryRange, [storeId])
  useEffect(() => setAppointmentPage(1), [storeId, search, status]); useEffect(() => { setAppointmentPage(1); setShiftPage(1) }, [storeId])

  const appointments = useQuery({ queryKey: ['appointments', storeId, range, search, status, appointmentPage], enabled: Boolean(storeId), queryFn: ({ signal }) => apiRequest<PageResult<Appointment>>(`/api/v1/scheduling/appointments?storeId=${storeId}&fromUtc=${encodeURIComponent(range.fromUtc)}&toUtc=${encodeURIComponent(range.toUtc)}&query=${encodeURIComponent(search)}&status=${status ?? ''}&page=${appointmentPage}&pageSize=20`, { signal }) })
  const shifts = useQuery({ queryKey: ['employee-shifts', storeId, range, shiftPage], enabled: Boolean(storeId), queryFn: () => apiRequest<PageResult<EmployeeShift>>(`/api/v1/scheduling/shifts?storeId=${storeId}&fromUtc=${encodeURIComponent(range.fromUtc)}&toUtc=${encodeURIComponent(range.toUtc)}&page=${shiftPage}&pageSize=20`) })
  const employees = useQuery({ queryKey: ['scheduling-employees', storeId], enabled: Boolean(storeId), queryFn: () => apiRequest<SchedulingResource[]>(`/api/v1/scheduling/employees?storeId=${storeId}`) })
  const facilities = useQuery({ queryKey: ['scheduling-facilities', storeId], enabled: Boolean(storeId), queryFn: () => apiRequest<SchedulingResource[]>(`/api/v1/scheduling/facilities?storeId=${storeId}`) })
  const customers = useQuery({ queryKey: ['customers', storeId, 'scheduling'], enabled: Boolean(storeId), queryFn: () => apiRequest<PageResult<CustomerSummary>>('/api/v1/customers/search', { method: 'POST', body: JSON.stringify({ storeId, query: '', page: 1, pageSize: 100 }) }), select: (result) => result.items.filter((item) => item.status === 'Active') })
  const serviceItems = useQuery({ queryKey: ['service-items'], queryFn: () => apiRequest<ServiceItem[]>('/api/v1/catalog/service-items'), select: (items) => items.filter((item) => item.status === 'ENABLED' || item.status === 'Enabled') })
  const refresh = async () => Promise.all([queryClient.invalidateQueries({ queryKey: ['appointments', storeId] }), queryClient.invalidateQueries({ queryKey: ['employee-shifts', storeId] }), queryClient.invalidateQueries({ queryKey: ['facility-board', storeId] })])
  const onError = (error: unknown) => message.error(error instanceof ApiError ? error.message : '操作失败')

  const saveAppointment = useMutation({ mutationFn: (values: AppointmentValues) => {
    if (!storeId || !isValidPeriod(values.startsAtLocal, values.endsAtLocal, 5)) throw new Error('预约结束时间至少晚于开始时间5分钟')
    const body = { storeId, customerId: values.customerId, serviceItemId: values.serviceItemId, employeeId: values.employeeId || null, facilityId: values.facilityId || null, startsAtUtc: toUtcIso(values.startsAtLocal), endsAtUtc: toUtcIso(values.endsAtLocal), note: values.note || null, ...(editingAppointment === 'new' ? { commandId: commandId() } : { expectedVersion: editingAppointment?.version }) }
    return editingAppointment === 'new' ? apiRequest<Appointment>('/api/v1/scheduling/appointments', { method: 'POST', body: JSON.stringify(body) }) : apiRequest<Appointment>(`/api/v1/scheduling/appointments/${editingAppointment?.id}`, { method: 'PUT', body: JSON.stringify(body) })
  }, onSuccess: async () => { message.success(editingAppointment === 'new' ? '预约已创建' : '预约已更新'); setEditingAppointment(undefined); await refresh() }, onError })
  const saveShift = useMutation({ mutationFn: (values: ShiftValues) => {
    if (!storeId || !isValidPeriod(values.startsAtLocal, values.endsAtLocal, 30)) throw new Error('班次结束时间至少晚于开始时间30分钟')
    const body = { storeId, employeeId: values.employeeId, startsAtUtc: toUtcIso(values.startsAtLocal), endsAtUtc: toUtcIso(values.endsAtLocal), note: values.note || null, ...(editingShift === 'new' ? { commandId: commandId() } : { expectedVersion: editingShift?.version }) }
    return editingShift === 'new' ? apiRequest<EmployeeShift>('/api/v1/scheduling/shifts', { method: 'POST', body: JSON.stringify(body) }) : apiRequest<EmployeeShift>(`/api/v1/scheduling/shifts/${editingShift?.id}`, { method: 'PUT', body: JSON.stringify(body) })
  }, onSuccess: async () => { message.success(editingShift === 'new' ? '班次已创建' : '班次已更新'); setEditingShift(undefined); await refresh() }, onError })
  const transition = useMutation({ mutationFn: ({ item, action, reason }: { item: Appointment; action: 'arrive' | 'cancel' | 'no-show'; reason?: string }) => apiRequest<Appointment>(`/api/v1/scheduling/appointments/${item.id}/${action}`, { method: 'POST', body: JSON.stringify({ storeId, expectedVersion: item.version, reason: reason || null, commandId: commandId() }) }), onSuccess: async (_data, variables) => { message.success(variables.action === 'arrive' ? '已转为到店接待，收费仍需单独录单' : variables.action === 'cancel' ? '预约已取消' : '已记录爽约'); await refresh() }, onError })
  const cancelShift = useMutation({ mutationFn: ({ item, reason }: { item: EmployeeShift; reason: string }) => apiRequest(`/api/v1/scheduling/shifts/${item.id}/cancel`, { method: 'POST', body: JSON.stringify({ storeId, expectedVersion: item.version, reason, commandId: commandId() }) }), onSuccess: async () => { message.success('班次已取消'); await refresh() }, onError })

  const openAppointment = (item: Appointment | 'new') => { setEditingAppointment(item); appointmentForm.resetFields(); appointmentForm.setFieldsValue(item === 'new' ? { ...defaultPeriod(), customerId: undefined, serviceItemId: undefined } : { customerId: item.customerId, serviceItemId: item.serviceItemId, employeeId: item.employeeId, facilityId: item.facilityId, startsAtLocal: toLocalDateTimeValue(item.startsAtUtc), endsAtLocal: toLocalDateTimeValue(item.endsAtUtc), note: item.note }) }
  const openShift = (item: EmployeeShift | 'new') => { setEditingShift(item); shiftForm.resetFields(); shiftForm.setFieldsValue(item === 'new' ? { ...defaultPeriod(8 * 60), employeeId: undefined } : { employeeId: item.employeeId, startsAtLocal: toLocalDateTimeValue(item.startsAtUtc), endsAtLocal: toLocalDateTimeValue(item.endsAtUtc), note: item.note }) }
  const askReason = (title: string, onOk: (reason: string) => void, required = true) => { let reason = ''; Modal.confirm({ title, content: <Input.TextArea rows={3} maxLength={500} placeholder={required ? '请填写原因' : '说明（可选）'} onChange={(event) => { reason = event.target.value }} />, okText: '确认', cancelText: '返回', onOk: () => { if (required && !reason.trim()) { message.error('请填写原因'); return Promise.reject() } onOk(reason.trim()) } }) }

  const appointmentColumns = [
    { title: '预约时间', key: 'time', width: 185, render: (_: unknown, item: Appointment) => <><strong>{dateTime(item.startsAtUtc)}</strong><br /><Typography.Text type="secondary">至 {dateTime(item.endsAtUtc)}</Typography.Text></> },
    { title: '顾客', key: 'customer', render: (_: unknown, item: Appointment) => <><strong>{item.customerName}</strong><br /><Typography.Text type="secondary">{item.maskedMobile}</Typography.Text></> },
    { title: '服务安排', key: 'service', render: (_: unknown, item: Appointment) => <><span>{item.serviceItemName}</span><br /><Typography.Text type="secondary">{item.employeeName ?? '未指定员工'} · {item.facilityName ?? '未指定设施'}</Typography.Text></> },
    { title: '状态', dataIndex: 'status', width: 90, render: (value: string) => <Tag color={appointmentStatus[value]?.color}>{appointmentStatus[value]?.label ?? value}</Tag> },
    { title: '操作', key: 'actions', width: 245, render: (_: unknown, item: Appointment) => item.status === 'Scheduled' ? <Space wrap><Button type="link" icon={<EditOutlined />} onClick={() => openAppointment(item)}>修改</Button><Button type="link" icon={<CheckCircleOutlined />} onClick={() => transition.mutate({ item, action: 'arrive' })}>到店</Button><Button type="link" danger onClick={() => askReason('取消预约', (reason) => transition.mutate({ item, action: 'cancel', reason }))}>取消</Button><Button type="link" icon={<StopOutlined />} onClick={() => askReason('记录爽约', (reason) => transition.mutate({ item, action: 'no-show', reason }), false)}>爽约</Button></Space> : <Typography.Text type="secondary">{item.status === 'Arrived' ? `接待 ${item.visitId?.slice(-8)}` : item.cancellationReason ?? item.noShowReason ?? '历史记录'}</Typography.Text> },
  ]
  const shiftColumns = [
    { title: '员工', key: 'employee', render: (_: unknown, item: EmployeeShift) => <><strong>{item.employeeName}</strong><br /><Typography.Text type="secondary">{item.employeeNo}</Typography.Text></> },
    { title: '班次', key: 'period', render: (_: unknown, item: EmployeeShift) => <>{dateTime(item.startsAtUtc)}<br /><Typography.Text type="secondary">至 {dateTime(item.endsAtUtc)}</Typography.Text></> },
    { title: '备注', dataIndex: 'note', render: (value?: string) => value || '—' },
    { title: '状态', dataIndex: 'status', render: (value: string) => <Tag color={shiftStatus[value]?.color}>{shiftStatus[value]?.label ?? value}</Tag> },
    { title: '操作', key: 'actions', render: (_: unknown, item: EmployeeShift) => item.status === 'Scheduled' ? <Space><Button type="link" icon={<EditOutlined />} onClick={() => openShift(item)}>修改</Button><Button type="link" danger onClick={() => askReason('取消班次', (reason) => cancelShift.mutate({ item, reason }))}>取消</Button></Space> : <Typography.Text type="secondary">{item.cancellationReason}</Typography.Text> },
  ]

  return <div className="page-stack">
    <div className="page-heading"><div><Typography.Title level={2}>预约与排班</Typography.Title><Typography.Paragraph>预约安排员工和设施；到店后转入设施接待，计时和最终收费仍保持独立。</Typography.Paragraph></div>{canOperate && <Button type="primary" icon={<PlusOutlined />} onClick={() => activeTab === 'appointments' ? openAppointment('new') : openShift('new')}>{activeTab === 'appointments' ? '新增预约' : '新增班次'}</Button>}</div>
    <Alert type="info" showIcon title="同一员工或设施的预约不可重叠；同一员工班次不可重叠。取消只改变状态并保留历史，不会删除记录。" />
    <Card><Tabs activeKey={activeTab} onChange={setActiveTab} items={[{ key: 'appointments', label: <Space><CalendarOutlined />预约</Space>, children: <><Space wrap className="table-toolbar"><Input.Search allowClear value={query} onChange={(event) => setQuery(event.target.value)} placeholder="自动查询顾客、手机号、预约号或项目" className="search-input" /><Select allowClear value={status} onChange={setStatus} placeholder="全部状态" options={Object.entries(appointmentStatus).map(([value, meta]) => ({ value, label: meta.label }))} /></Space>{appointments.error && <Alert type="error" showIcon title={appointments.error instanceof Error ? appointments.error.message : '预约加载失败'} />}<Table rowKey="id" loading={appointments.isLoading} dataSource={appointments.data?.items ?? []} columns={appointmentColumns} pagination={false} scroll={{ x: 1000 }} /><Pagination current={appointmentPage} pageSize={20} total={appointments.data?.total ?? 0} showSizeChanger={false} onChange={setAppointmentPage} /></> }, { key: 'shifts', label: <Space><TeamOutlined />员工排班</Space>, disabled: !isManager, children: <><Table rowKey="id" loading={shifts.isLoading} dataSource={shifts.data?.items ?? []} columns={shiftColumns} pagination={false} scroll={{ x: 800 }} /><Pagination current={shiftPage} pageSize={20} total={shifts.data?.total ?? 0} showSizeChanger={false} onChange={setShiftPage} /></> }]} /></Card>

    <Modal title={editingAppointment === 'new' ? '新增预约' : '修改预约'} open={Boolean(editingAppointment)} onCancel={() => setEditingAppointment(undefined)} onOk={() => appointmentForm.submit()} okText="保存" confirmLoading={saveAppointment.isPending} destroyOnHidden><Form form={appointmentForm} layout="vertical" onFinish={(values) => saveAppointment.mutate(values)}><Form.Item name="customerId" label="顾客" rules={[{ required: true, message: '请选择顾客' }]}><Select showSearch optionFilterProp="label" loading={customers.isLoading} options={customers.data?.map((item) => ({ value: item.id, label: `${item.displayName} · ${item.maskedMobile}` }))} /></Form.Item><Form.Item name="serviceItemId" label="服务项目" rules={[{ required: true, message: '请选择服务项目' }]}><Select showSearch optionFilterProp="label" loading={serviceItems.isLoading} options={serviceItems.data?.map((item) => ({ value: item.id, label: `${item.name} · ${item.standardDurationMinutes}分钟` }))} /></Form.Item><Space align="start" className="full-width"><Form.Item name="employeeId" label="服务员工（可选）" className="grow"><Select allowClear showSearch optionFilterProp="label" options={employees.data?.map((item) => ({ value: item.id, label: `${item.name} · ${item.code}` }))} /></Form.Item><Form.Item name="facilityId" label="预约设施（可选）" className="grow"><Select allowClear showSearch optionFilterProp="label" placeholder={facilities.data?.length ? '选择允许预约的设施' : '暂无启用预约的设施'} options={facilities.data?.map((item) => ({ value: item.id, label: `${item.name} · ${item.code}` }))} /></Form.Item></Space><Space align="start" className="full-width"><Form.Item name="startsAtLocal" label="开始时间" rules={[{ required: true }]} className="grow"><Input type="datetime-local" /></Form.Item><Form.Item name="endsAtLocal" label="结束时间" rules={[{ required: true }]} className="grow"><Input type="datetime-local" /></Form.Item></Space><Form.Item name="note" label="备注（可选）" rules={[{ max: 500 }]}><Input.TextArea rows={3} maxLength={500} showCount /></Form.Item></Form></Modal>
    <Modal title={editingShift === 'new' ? '新增员工班次' : '修改员工班次'} open={Boolean(editingShift)} onCancel={() => setEditingShift(undefined)} onOk={() => shiftForm.submit()} okText="保存" confirmLoading={saveShift.isPending} destroyOnHidden><Form form={shiftForm} layout="vertical" onFinish={(values) => saveShift.mutate(values)}><Form.Item name="employeeId" label="员工" rules={[{ required: true }]}><Select disabled={editingShift !== 'new'} showSearch optionFilterProp="label" options={employees.data?.map((item) => ({ value: item.id, label: `${item.name} · ${item.code}` }))} /></Form.Item><Space align="start" className="full-width"><Form.Item name="startsAtLocal" label="上班时间" rules={[{ required: true }]} className="grow"><Input type="datetime-local" /></Form.Item><Form.Item name="endsAtLocal" label="下班时间" rules={[{ required: true }]} className="grow"><Input type="datetime-local" /></Form.Item></Space><Form.Item name="note" label="备注（可选）" rules={[{ max: 500 }]}><Input.TextArea rows={3} maxLength={500} showCount /></Form.Item></Form></Modal>
  </div>
}
