import { PlusOutlined } from '@ant-design/icons'
import { Alert, Button, Card, DatePicker, Form, Input, InputNumber, Modal, Select, Space, Table, Tabs, Tag, Typography, message } from 'antd'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import type { Dayjs } from 'dayjs'
import { ApiError, apiRequest } from '../api/client'
import type { InventoryBalance, InventoryLot, InventoryTransfer, PageResult, PurchaseReceipt, Stocktake, Supplier } from '../api/types'
import { useAuth } from '../auth/useAuth'

type Line = { productItemId: string; quantity: number; countedQuantity: number; unitCostYuan: number; batchNo: string; expiresOn?: Dayjs }
type Dialog = 'supplier' | 'purchase' | 'stocktake' | 'transfer'
const commandId = () => crypto.randomUUID()
const money = (minor: number) => `¥${(minor / 100).toFixed(2)}`
const labels: Record<string, string> = { Active: '启用', Disabled: '停用', PendingApproval: '待审批', Posted: '已过账', Cancelled: '已取消', Requested: '待出库', InTransit: '在途', Received: '已收货' }

export function SupplyChainPage() {
  const auth = useAuth(); const storeId = auth.store?.id; const owner = auth.user?.roles.includes('OWNER') ?? false
  const cache = useQueryClient(); const [dialog, setDialog] = useState<Dialog>(); const [form] = Form.useForm()
  const balances = useQuery({ queryKey: ['inventory-balances', storeId], enabled: Boolean(storeId), queryFn: () => apiRequest<InventoryBalance[]>(`/api/v1/inventory/balances?storeId=${storeId}`) })
  const suppliers = useQuery({ queryKey: ['suppliers'], queryFn: () => apiRequest<PageResult<Supplier>>('/api/v1/supply-chain/suppliers?includeDisabled=true&page=1&pageSize=100') })
  const lots = useQuery({ queryKey: ['inventory-lots', storeId], enabled: Boolean(storeId), queryFn: () => apiRequest<PageResult<InventoryLot>>(`/api/v1/supply-chain/lots?storeId=${storeId}&page=1&pageSize=100`) })
  const purchases = useQuery({ queryKey: ['purchase-receipts', storeId], enabled: Boolean(storeId && owner), queryFn: () => apiRequest<PageResult<PurchaseReceipt>>(`/api/v1/supply-chain/purchase-receipts?storeId=${storeId}&page=1&pageSize=50`) })
  const stocktakes = useQuery({ queryKey: ['stocktakes', storeId], enabled: Boolean(storeId), queryFn: () => apiRequest<PageResult<Stocktake>>(`/api/v1/supply-chain/stocktakes?storeId=${storeId}&page=1&pageSize=50`) })
  const transfers = useQuery({ queryKey: ['inventory-transfers', storeId], enabled: Boolean(storeId), queryFn: () => apiRequest<PageResult<InventoryTransfer>>(`/api/v1/supply-chain/transfers?storeId=${storeId}&page=1&pageSize=50`) })
  const products = useMemo(() => balances.data?.filter((item) => item.trackInventory) ?? [], [balances.data])
  const productOptions = products.map((item) => ({ value: item.productItemId, label: `${item.productName} · ${item.productCode}` }))
  const refresh = async () => Promise.all(['inventory-balances', 'inventory-lots', 'purchase-receipts', 'stocktakes', 'inventory-transfers', 'suppliers'].map((key) => cache.invalidateQueries({ queryKey: [key] })))
  const failure = (error: Error) => message.error(error instanceof ApiError ? error.message : '操作失败')
  const submit = useMutation({ mutationFn: async (values: Record<string, unknown>) => {
    if (dialog === 'supplier') return apiRequest('/api/v1/supply-chain/suppliers', { method: 'POST', body: JSON.stringify(values) })
    const lines = values.lines as Line[]
    if (dialog === 'purchase') return apiRequest('/api/v1/supply-chain/purchase-receipts', { method: 'POST', body: JSON.stringify({ ...values, storeId, commandId: commandId(), lines: lines.map((line) => ({ productItemId: line.productItemId, quantity: line.quantity, unitCostMinor: Math.round(line.unitCostYuan * 100), batchNo: line.batchNo, expiresOn: line.expiresOn?.format('YYYY-MM-DD') })) }) })
    if (dialog === 'stocktake') return apiRequest('/api/v1/supply-chain/stocktakes', { method: 'POST', body: JSON.stringify({ storeId, reason: values.reason, commandId: commandId(), lines: lines.map((line) => ({ productItemId: line.productItemId, countedQuantity: line.countedQuantity })) }) })
    return apiRequest('/api/v1/supply-chain/transfers', { method: 'POST', body: JSON.stringify({ sourceStoreId: storeId, destinationStoreId: values.destinationStoreId, reason: values.reason, commandId: commandId(), lines: lines.map((line) => ({ productItemId: line.productItemId, quantity: line.quantity })) }) })
  }, onSuccess: async () => { message.success(dialog === 'supplier' ? '供应商已创建' : dialog === 'stocktake' ? '盘点单已提交审批' : dialog === 'transfer' ? '调拨单已创建' : '采购入库已过账'); setDialog(undefined); form.resetFields(); await refresh() }, onError: failure })
  const transition = useMutation({ mutationFn: ({ path, version, includeStore }: { path: string; version: number; includeStore?: boolean }) => apiRequest(path, { method: 'POST', body: JSON.stringify({ ...(includeStore ? { storeId } : {}), reason: '操作复核无误', expectedVersion: version, commandId: commandId() }) }), onSuccess: refresh, onError: failure })
  const open = (value: Dialog) => { form.resetFields(); form.setFieldsValue(value === 'supplier' ? {} : { reason: value === 'stocktake' ? '库存实物盘点' : value === 'transfer' ? '门店库存调拨' : undefined, note: value === 'purchase' ? '采购到货验收入库' : undefined, lines: [value === 'stocktake' ? { countedQuantity: 0 } : { quantity: 1, unitCostYuan: 0 }] }); setDialog(value) }
  const lineEditor = dialog && dialog !== 'supplier' ? <Form.List name="lines">{(fields, actions) => <Space direction="vertical" className="full-width">{fields.map((field) => <Space key={field.key} wrap align="baseline"><Form.Item name={[field.name, 'productItemId']} rules={[{ required: true, message: '请选择产品' }]}><Select className="product-line-select" showSearch optionFilterProp="label" placeholder="产品" options={productOptions} /></Form.Item>{dialog === 'stocktake' ? <Form.Item name={[field.name, 'countedQuantity']} rules={[{ required: true }]}><InputNumber min={0} precision={0} placeholder="实盘数量" /></Form.Item> : <Form.Item name={[field.name, 'quantity']} rules={[{ required: true }]}><InputNumber min={1} precision={0} placeholder="数量" /></Form.Item>}{dialog === 'purchase' && <><Form.Item name={[field.name, 'unitCostYuan']} rules={[{ required: true }]}><InputNumber min={0} precision={2} placeholder="单位成本(元)" /></Form.Item><Form.Item name={[field.name, 'batchNo']} rules={[{ required: true }]}><Input placeholder="批次号" /></Form.Item><Form.Item name={[field.name, 'expiresOn']}><DatePicker placeholder="有效期（可选）" /></Form.Item></>}<Button danger onClick={() => actions.remove(field.name)}>移除</Button></Space>)}<Button block icon={<PlusOutlined />} onClick={() => actions.add(dialog === 'stocktake' ? { countedQuantity: 0 } : { quantity: 1, unitCostYuan: 0 })}>添加产品行</Button></Space>}</Form.List> : null
  const lotView = <Card variant="borderless"><Alert className="section-alert" type="info" showIcon title="按有效期优先出库；采购成本仅最高权限可见。" /><Table rowKey="id" dataSource={lots.data?.items} loading={lots.isLoading} pagination={false} columns={[{ title: '产品', render: (_: unknown, x: InventoryLot) => `${x.productName} · ${x.productCode}` }, { title: '批次', dataIndex: 'batchNo' }, { title: '有效期', dataIndex: 'expiresOn', render: (x?: string) => x ?? '长期' }, { title: '剩余', render: (_: unknown, x: InventoryLot) => `${x.remainingQuantity}/${x.originalQuantity} ${x.unitName}` }, ...(owner ? [{ title: '单位成本', dataIndex: 'unitCostMinor', render: money }] : [])]} /></Card>
  const stocktakeView = <Card variant="borderless" extra={<Button type="primary" onClick={() => open('stocktake')}>发起盘点</Button>}><Table rowKey="id" dataSource={stocktakes.data?.items} pagination={false} columns={[{ title: '单号', dataIndex: 'stocktakeNo' }, { title: '盘点原因', dataIndex: 'reason' }, { title: '差异数量', render: (_: unknown, x: Stocktake) => x.lines.reduce((sum, line) => sum + Math.abs(line.differenceQuantity), 0) }, { title: '状态', dataIndex: 'status', render: (x: string) => <Tag>{labels[x] ?? x}</Tag> }, { title: '操作', render: (_: unknown, x: Stocktake) => x.status === 'PendingApproval' ? <Space>{owner && x.requestedBy !== auth.user?.id && <Button size="small" type="primary" onClick={() => transition.mutate({ path: `/api/v1/supply-chain/stocktakes/${x.id}/approve`, version: x.version, includeStore: true })}>审批过账</Button>}<Button size="small" danger onClick={() => transition.mutate({ path: `/api/v1/supply-chain/stocktakes/${x.id}/cancel`, version: x.version, includeStore: true })}>取消</Button></Space> : '—' }]} /></Card>
  const transferView = <Card variant="borderless" extra={owner && <Button type="primary" disabled={(auth.user?.stores.length ?? 0) < 2} onClick={() => open('transfer')}>新建调拨</Button>}><Table rowKey="id" dataSource={transfers.data?.items} pagination={false} columns={[{ title: '单号', dataIndex: 'transferNo' }, { title: '状态', dataIndex: 'status', render: (x: string) => <Tag>{labels[x] ?? x}</Tag> }, { title: '原因', dataIndex: 'reason' }, { title: '操作', render: (_: unknown, x: InventoryTransfer) => owner ? <Space>{x.status === 'Requested' && <><Button size="small" onClick={() => transition.mutate({ path: `/api/v1/supply-chain/transfers/${x.id}/ship`, version: x.version })}>确认出库</Button><Button danger size="small" onClick={() => transition.mutate({ path: `/api/v1/supply-chain/transfers/${x.id}/cancel`, version: x.version })}>取消</Button></>}{x.status === 'InTransit' && <Button type="primary" size="small" onClick={() => transition.mutate({ path: `/api/v1/supply-chain/transfers/${x.id}/receive`, version: x.version })}>确认收货</Button>}</Space> : '—' }]} /></Card>
  const supplierView = <Card variant="borderless" extra={owner && <Button type="primary" onClick={() => open('supplier')}>新增供应商</Button>}><Table rowKey="id" dataSource={suppliers.data?.items} pagination={false} columns={[{ title: '编码', dataIndex: 'code' }, { title: '供应商', dataIndex: 'name' }, { title: '联系人', dataIndex: 'contactName', render: (x?: string) => x ?? '—' }, { title: '联系电话', dataIndex: 'mobile', render: (x?: string) => x ?? '—' }, { title: '状态', dataIndex: 'status', render: (x: string) => <Tag>{labels[x] ?? x}</Tag> }]} /></Card>
  const purchaseView = owner ? <Card variant="borderless" extra={<Button type="primary" onClick={() => open('purchase')}>采购入库</Button>}><Table rowKey="id" dataSource={purchases.data?.items} pagination={false} columns={[{ title: '单号', dataIndex: 'receiptNo' }, { title: '供应商', dataIndex: 'supplierName' }, { title: '采购金额', dataIndex: 'totalCostMinor', render: money }, { title: '入库时间', dataIndex: 'postedAtUtc', render: (x: string) => new Date(x).toLocaleString('zh-CN') }, { title: '说明', dataIndex: 'note' }]} /></Card> : <Alert type="info" showIcon title="采购成本和入库明细仅最高权限可查看。" />
  return <div className="page-stack"><div className="page-heading"><div><Typography.Title level={2}>采购与供应链</Typography.Title><Typography.Paragraph>供应商、采购成本、批次效期、盘点和跨店调拨集中管理，过账流水不可修改。</Typography.Paragraph></div></div><Tabs items={[{ key: 'lots', label: '批次效期', children: lotView }, { key: 'stocktakes', label: '库存盘点', children: stocktakeView }, { key: 'transfers', label: '跨店调拨', children: transferView }, { key: 'suppliers', label: '供应商', children: supplierView }, { key: 'purchases', label: '采购入库', children: purchaseView }]} /><Modal width={dialog === 'purchase' ? 1000 : 760} title={dialog === 'supplier' ? '新增供应商' : dialog === 'purchase' ? '采购入库' : dialog === 'stocktake' ? '发起库存盘点' : '新建跨店调拨'} open={Boolean(dialog)} onCancel={() => setDialog(undefined)} onOk={() => form.submit()} confirmLoading={submit.isPending}><Form form={form} layout="vertical" onFinish={(values: Record<string, unknown>) => submit.mutate(values)}>{dialog === 'supplier' && <><Form.Item name="code" label="供应商编码" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="name" label="供应商名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="contactName" label="联系人（可选）"><Input /></Form.Item><Form.Item name="mobile" label="联系电话（可选）"><Input /></Form.Item><Form.Item name="settlementTerms" label="结算条款（可选）"><Input.TextArea /></Form.Item></>}{dialog === 'purchase' && <><Form.Item name="supplierId" label="供应商" rules={[{ required: true }]}><Select options={suppliers.data?.items.filter((x) => x.status === 'Active').map((x) => ({ value: x.id, label: `${x.name} · ${x.code}` }))} /></Form.Item><Form.Item name="externalNo" label="供应商单号（可选）"><Input /></Form.Item><Form.Item name="note" label="入库说明" rules={[{ required: true }]}><Input /></Form.Item></>}{dialog === 'transfer' && <Form.Item name="destinationStoreId" label="调入门店" rules={[{ required: true }]}><Select options={auth.user?.stores.filter((x) => x.id !== storeId).map((x) => ({ value: x.id, label: x.name }))} /></Form.Item>}{(dialog === 'stocktake' || dialog === 'transfer') && <Form.Item name="reason" label={dialog === 'stocktake' ? '盘点原因' : '调拨原因'} rules={[{ required: true }]}><Input /></Form.Item>}{lineEditor}</Form></Modal></div>
}
