export interface PageResult<T> { items: T[]; total: number; page: number; pageSize: number }
export interface AuthorizedStore { id: string; code: string; name: string; isDefault: boolean }
export interface CurrentUser { id: string; tenantId: string; displayName: string; account: string; mustChangePassword: boolean; roles: string[]; permissions: string[]; stores: AuthorizedStore[] }
export interface EmployeeStore { id: string; code: string; name: string; isPrimary: boolean }
export interface Employee { id: string; employeeNo: string; displayName: string; positionCode: string; status: string; userId?: string; account?: string; accountEnabled?: boolean; mustChangePassword?: boolean; roles: string[]; stores: EmployeeStore[]; createdAtUtc: string; version: number }
export interface EmployeeRole { id: string; code: string; name: string }
export interface EmployeePosition { id: string; code: string; name: string; sortOrder: number; status: string; version: number }
export interface BrandProfile { id: string; code: string; name: string; status: string; version: number }
export interface StoreProfile { id: string; code: string; name: string; timeZoneId: string; address?: string; status: string; managerNames: string[]; employeeCount: number; facilityGroupCount: number; facilityCount: number; enabledFacilityCount: number; version: number }
export interface OrganizationSettings { brand: BrandProfile; stores: StoreProfile[] }
export interface NavigationLabels { labels: Record<string, string>; version: number }
export interface ServiceItem { id: string; code: string; name: string; standardDurationMinutes: number; status: string; version: number; commissionMode?: string; commissionRateBasisPoints?: number; commissionFixedMinor?: number }
export interface ProductItem { id: string; code: string; name: string; unitName: string; trackInventory: boolean; imageFileId?: string; status: string; version: number }
export interface PriceBookLine { serviceItemId: string; serviceItemName: string; unitPriceMinor: number }
export interface ProductPriceBookLine { productItemId: string; productItemName: string; unitName: string; unitPriceMinor: number }
export interface PriceBook { id: string; name: string; status: string; effectiveFrom: string; publishedAtUtc?: string; lines: PriceBookLine[]; productLines: ProductPriceBookLine[]; version: number }

export interface FacilityGroup { id: string; displayName: string; sortOrder: number }
export interface FacilityType { id: string; displayName: string }
export interface FacilityConfigurationStore { id: string; code: string; name: string; status: string; managerNames: string[]; groupCount: number; facilityCount: number; enabledFacilityCount: number }
export interface FacilityConfigurationItem { id: string; groupId: string; facilityTypeId: string; typeName: string; code: string; displayName: string; serviceName?: string | null; equipmentName?: string | null; referencePriceMinor?: number | null; sortOrder: number; defaultCleaningMinutes: number; allowReservation: boolean; lifecycleStatus: string; version: number; hasOpenSession: boolean }
export interface FacilityConfigurationGroup { id: string; displayName: string; sortOrder: number; version: number; facilities: FacilityConfigurationItem[] }
export interface FacilityConfiguration { storeId: string; storeCode: string; storeName: string; managerNames: string[]; groups: FacilityConfigurationGroup[] }
export interface FacilityBoardItem {
  id: string; code: string; displayName: string; typeName: string; status: string; version: number
  sessionId?: string; visitId?: string; visitNo?: string; sessionStatus?: string; startedAtUtc?: string
  activeSeconds: number; pausedSeconds: number; expectedDurationMinutes?: number; note?: string
  serviceName?: string | null; equipmentName?: string | null; referencePriceMinor?: number | null
  customerId?: string | null; customerDisplayName?: string | null
  plannedServiceItemId?: string | null; plannedServiceItemName?: string | null
}
export interface FacilityBoardGroup { id: string; displayName: string; facilities: FacilityBoardItem[] }
export interface FacilityBoard { serverNowUtc: string; groups: FacilityBoardGroup[] }

export interface Appointment { id: string; appointmentNo: string; storeId: string; customerId: string; customerName: string; maskedMobile: string; serviceItemId: string; serviceItemName: string; employeeId?: string; employeeName?: string; facilityId?: string; facilityName?: string; startsAtUtc: string; endsAtUtc: string; note?: string; status: string; visitId?: string; arrivedAtUtc?: string; cancellationReason?: string; noShowReason?: string; version: number }
export interface EmployeeShift { id: string; storeId: string; employeeId: string; employeeNo: string; employeeName: string; startsAtUtc: string; endsAtUtc: string; note?: string; status: string; cancellationReason?: string; version: number }
export interface SchedulingResource { id: string; code: string; name: string }

export interface CustomerSummary { id: string; displayName: string; maskedMobile: string; status: string; homeStoreId: string; homeStoreName: string; activeCardCount: number; createdAtUtc: string }
export interface MemberCardType { id: string; code: string; name: string; validityDays?: number; status: string }
export interface MemberAccount { id: string; accountType: string; balanceUnits: number; status: string }
export interface MemberCard { id: string; cardTypeName: string; maskedCardNo: string; status: string; validFrom: string; validTo?: string; accounts: MemberAccount[] }
export interface MergedCustomerAlias { id: string; displayName: string; maskedMobile: string; mergedAtUtc?: string }
export interface CustomerDetail { id: string; displayName: string; maskedMobile: string; gender: string; birthDate?: string; residence?: string; sourceCode?: string; serviceNotificationConsent: boolean; marketingConsent: boolean; status: string; homeStoreId: string; homeStoreName: string; version: number; cards: MemberCard[]; mergedAliases: MergedCustomerAlias[] }
export interface CustomerMergePreview { sourceCustomerId: string; sourceDisplayName: string; sourceMaskedMobile: string; sourceVersion: number; targetCustomerId: string; targetDisplayName: string; targetMaskedMobile: string; targetVersion: number; sourceCardCount: number; sourcePrincipalBalanceMinor: number; sourceBonusBalanceMinor: number; sourcePointsBalance: number; sourceOrderCount: number; sourceServiceRecordCount: number; blockers: string[]; canMerge: boolean }
export interface ServiceRecordAttachment { fileId: string; fileName: string; contentType: string; sizeBytes: number }
export interface ServiceRecordCorrection { id: string; reason: string; conditionNotes?: string; serviceContent?: string; followUpNotes?: string; correctedBy: string; correctedByName: string; createdAtUtc: string }
export interface ServiceRecordCategory { id: string; code: string; name: string; sortOrder: number; status: string; version: number }
export interface ServiceRecord { id: string; storeId: string; customerId: string; categoryId?: string; categoryCode?: string; categoryName?: string; serviceOrderId?: string; serviceOrderNo?: string; serviceOccurredAtUtc: string; conditionNotes?: string; serviceContent?: string; followUpNotes?: string; createdBy: string; createdByName: string; createdAtUtc: string; attachments: ServiceRecordAttachment[]; corrections: ServiceRecordCorrection[] }
export interface ServiceRecordOverview { id: string; storeId: string; customerId: string; customerName: string; maskedMobile: string; homeStoreName: string; categoryId?: string; categoryCode?: string; categoryName?: string; serviceOrderId?: string; serviceOrderNo?: string; serviceOccurredAtUtc: string; conditionNotes?: string; serviceContent?: string; followUpNotes?: string; createdBy: string; createdByName: string; createdAtUtc: string; attachmentCount: number; correctionCount: number }
export interface ServiceRecordOrderOption { id: string; orderNo: string; status: string; createdAtUtc: string }
export interface CashierVisit { id: string; visitNo: string; status: string; customerId?: string; customerDisplayName: string; plannedServiceItemId?: string; plannedServiceItemName?: string; facilityNames: string; arrivedAtUtc: string; serviceEndedAtUtc?: string; facilitySeconds: number; note?: string }
export interface ServiceOrderLine { id: string; lineType: 'Service' | 'Product'; serviceItemId?: string; productItemId?: string; itemCode: string; itemName: string; unitName?: string; quantity: number; returnedQuantity: number; actualSeconds?: number; referencePriceMinor: number; enteredPriceMinor: number; lineAmountMinor: number; priceOverrideReason?: string; serviceEmployeeId?: string; employeeNo?: string; employeeName?: string }
export interface ServiceEmployee { id: string; employeeNo: string; displayName: string; positionCode: string; positionName: string }
export interface ServiceOrder { id: string; orderNo: string; visitId: string; customerId?: string; consultantEmployeeId?: string; consultantEmployeeNo?: string; consultantEmployeeName?: string; status: string; sourceChannel?: string; manualTicketNo?: string; maleGuestCount: number; maleAgeBand?: string; femaleGuestCount: number; femaleAgeBand?: string; priceBookId?: string | null; referenceAmountMinor: number; receivableMinor: number; refundedMinor: number; note?: string; version: number; createdAtUtc: string; priceAuthorizationStatus: string; pricePolicyId?: string; pricePolicyVersion?: number; priceAuthorizedBy?: string; priceAuthorizedAtUtc?: string; lines: ServiceOrderLine[] }
export interface ServiceOrderPrebillLine { lineType: 'Service' | 'Product'; itemCode: string; itemName: string; unitName?: string; quantity: number; unitPriceMinor: number; lineAmountMinor: number; employeeName?: string }
export interface ServiceOrderPrebill { id: string; prebillNo: string; orderId: string; orderNo: string; storeName: string; customerDisplayName: string; consultantEmployeeName?: string; receivableMinor: number; generatedAtUtc: string; lines: ServiceOrderPrebillLine[] }
export interface PriceOverridePolicy { id: string; policyVersion: number; managerLineDiscountBasisPoints: number; managerOrderDiscountMinor: number; allowManagerPriceIncrease: boolean; effectiveFromUtc: string; version: number }
export interface PriceOverrideApproval { id: string; serviceOrderId: string; orderNo: string; status: string; requesterId: string; requesterName: string; requesterRole: string; policyId: string; policyVersion: number; referenceAmountMinor: number; receivableMinor: number; differenceMinor: number; maximumLineDiscountBasisPoints: number; managerLineDiscountBasisPoints: number; managerOrderDiscountMinor: number; allowManagerPriceIncrease: boolean; requestedAtUtc: string; decidedBy?: string; deciderName?: string; decidedAtUtc?: string; decisionNote?: string; version: number }
export interface PaymentMethod { id: string; code: string; name: string; category: string; requiresOpenShift: boolean; internalAccountType?: string; channelProvider?: string }
export interface PaymentChannelConfiguration { id: string; storeId: string; provider: string; environment: string; displayName: string; credentialProfile: string; isEnabled: boolean; credentialsPresent: boolean; missingRequirements: string[]; version: number }
export interface PaymentChannelOrder { id: string; configurationId: string; paymentId: string; paymentAllocationId: string; provider: string; outTradeNo: string; amountMinor: number; status: string; qrPayload?: string; providerTradeNo?: string; failureCode?: string; expiresAtUtc: string; paidAtUtc?: string; closedAtUtc?: string; lastQueriedAtUtc?: string; paymentStatus: string; serviceOrderStatus: string; version: number }
export interface PaymentChannelReconciliationItem { id: string; itemType: string; status: string; matchKey: string; outTradeNo?: string; outRefundNo?: string; providerTradeNo?: string; paymentAllocationId?: string; channelRefundId?: string; localAmountMinor?: number; channelAmountMinor?: number; channelFeeMinor: number; localStatus?: string; channelStatus?: string; resolvedBy?: string; resolvedAtUtc?: string; resolutionReason?: string; version: number }
export interface PaymentChannelReconciliationRun { id: string; configurationId: string; provider: string; businessDate: string; attemptNo: number; status: string; channelEntryCount: number; matchedCount: number; differenceCount: number; sourceSha256?: string; failureCode?: string; startedBy: string; startedAtUtc: string; completedAtUtc?: string; version: number; items: PaymentChannelReconciliationItem[] }
export interface PaymentAllocation { id: string; methodId: string; methodCode: string; methodName: string; category: string; amountMinor: number; externalReference?: string; confirmationStatus: string; reconciliationStatus: string; shiftId?: string; memberAccountId?: string; channelProvider?: string }
export interface Payment { id: string; paymentNo: string; orderId?: string; businessType: string; businessId: string; status: string; currency: string; receivableMinor: number; paidMinor: number; refundedMinor: number; cashTenderedMinor?: number; cashChangeMinor?: number; paidAtUtc?: string; version: number; allocations: PaymentAllocation[] }
export interface PaymentReceiptLine { lineType: 'Service' | 'Product'; itemCode: string; itemName: string; unitName?: string; quantity: number; unitPriceMinor: number; amountMinor: number; employeeName?: string }
export interface PaymentReceipt { paymentId: string; paymentNo: string; orderNo: string; storeName: string; storeAddress?: string; facilityNumbers: string[]; customerName: string; customerMobile: string; operatorName: string; paidAtUtc: string; printedAtUtc: string; printSequence: number; printLabel: string; referenceAmountMinor: number; discountMinor: number; receivableMinor: number; groupBuyAmountMinor: number; groupBuyPlatform?: string; cashTenderedMinor?: number; cashChangeMinor?: number; lines: PaymentReceiptLine[]; allocations: PaymentAllocation[] }
export interface RefundLine { id: string; originalAllocationId: string; amountMinor: number; category: string; memberAccountId?: string; route: string; cashShiftId?: string; completedAtUtc?: string }
export interface ChannelRefund { id: string; provider: string; outRefundNo: string; providerRefundNo?: string; amountMinor: number; status: string; failureCode?: string; lastQueriedAtUtc?: string; succeededAtUtc?: string; version: number }
export interface Refund { id: string; paymentId: string; businessType: string; businessId: string; refundNo: string; status: string; amountMinor: number; reason: string; requestedBy: string; requestedAtUtc: string; approvedBy?: string; completedAtUtc?: string; rejectionReason?: string; version: number; lines: RefundLine[]; channelRefund?: ChannelRefund }
export interface MemberVerification { id: string; orderId: string; customerId: string; authorizedAmountMinor: number; maskedMobile: string; status: string; attemptsRemaining: number; expiresAtUtc: string; developmentCode?: string }
export interface MemberTopup { id: string; topupNo: string; storeId: string; customerId: string; cardId: string; principalMinor: number; bonusMinor: number; receivableMinor: number; status: string; note?: string; refundedPrincipalMinor: number; revokedBonusMinor: number; remainingPrincipalMinor: number; paidAtUtc: string; paymentId: string; paymentNo: string; paymentStatus: string; paymentRefundedMinor: number; paymentVersion: number; allocations: PaymentAllocation[] }
export interface ServicePassLedger { id: string; storeId: string; action: string; purchasedUsesDelta: number; bonusUsesDelta: number; purchasedUsesAfter: number; bonusUsesAfter: number; serviceOrderId?: string; reversedLedgerId?: string; reason: string; occurredAtUtc: string }
export interface ServicePass { id: string; storeId: string; customerId: string; cardId: string; serviceItemId: string; serviceItemName: string; passName: string; purchasedUses: number; bonusUses: number; remainingPurchasedUses: number; remainingBonusUses: number; remainingUses: number; validFrom: string; validTo?: string; status: string; version: number; ledgers: ServicePassLedger[] }
export interface PointGrant { id: string; originalUnits: number; remainingUnits: number; expiresOn?: string; sourceType: string; status: string }
export interface PointLedger { id: string; businessType: string; businessId: string; direction: string; units: number; balanceBefore: number; balanceAfter: number; occurredAtUtc: string }
export interface MemberPointSummary { cardId: string; accountId: string; balanceUnits: number; accountVersion: number; grants: PointGrant[]; ledgers: PointLedger[] }
export interface MembershipBenefits { servicePasses: ServicePass[]; pointAccounts: MemberPointSummary[] }
export interface CashierShift { id: string; shiftNo: string; operatorId: string; status: string; openingCashMinor: number; expectedCashMinor?: number; submittedCashMinor?: number; cashDifferenceMinor?: number; pendingReconciliationMinor?: number; handoverNote?: string; openedAtUtc: string; submittedAtUtc?: string; reviewedBy?: string; reviewReason?: string; closedAtUtc?: string; version: number }
export interface CashierShiftReview { shift: CashierShift; operatorDisplayName: string }
export interface AuditEvent { id: string; action: string; entityType: string; entityId?: string; previousState?: string; currentState?: string; reason?: string; operatorId?: string; operatorDisplayName: string; requestId?: string; traceId: string; occurredAtUtc: string }
export interface AuditEventPage { items: AuditEvent[]; total: number; page: number; pageSize: number }
export interface NotificationItem { id: string; type: string; title: string; description: string; severity: string; targetUrl: string; occurredAtUtc: string }
export interface NotificationInbox { pendingCount: number; items: NotificationItem[] }
export interface OperationsSummary { settledRevenueMinor: number; recordedFundsMinor: number; pendingReconciliationMinor: number; refundMinor: number; netRevenueMinor: number; todayRevenueMinor: number; settledOrderCount: number; visitCount: number; averageTicketMinor: number; facilityActiveSeconds: number; storedValuePrincipalMinor: number; storedValueBonusMinor: number; storedValueNetMinor: number }
export interface DailyOperations { date: string; settledRevenueMinor: number; recordedFundsMinor: number; pendingReconciliationMinor: number; refundMinor: number; netRevenueMinor: number; orderCount: number; visitCount: number; facilityActiveSeconds: number }
export interface PaymentMix { methodCode: string; methodName: string; amountMinor: number; pendingReconciliationMinor: number; refundMinor: number; netAmountMinor: number; allocationCount: number }
export interface ServicePerformance { serviceItemId: string; itemCode: string; itemName: string; quantity: number; revenueMinor: number; orderCount: number }
export interface EmployeeCommission { employeeId: string; employeeNo: string; employeeName: string; serviceQuantity: number; orderCount: number; grossServiceRevenueMinor: number; grossCommissionMinor: number; refundDeductionMinor: number; netCommissionMinor: number }
export interface FacilityUsage { facilityId: string; facilityName: string; activeSeconds: number; usageShare: number }
export interface OperationsReport { fromDate: string; toDate: string; timeZoneId: string; summary: OperationsSummary; daily: DailyOperations[]; paymentMix: PaymentMix[]; services: ServicePerformance[]; employeeCommissions: EmployeeCommission[]; facilities: FacilityUsage[] }
export interface StoreFinancialOverview { storeId: string; storeCode: string; storeName: string; timeZoneId: string; localDate: string; todayRevenueMinor: number; periodRevenueMinor: number; periodRefundMinor: number; periodNetRevenueMinor: number; storedValuePrincipalMinor: number; storedValueBonusMinor: number; storedValueNetMinor: number; pendingReconciliationMinor: number; pendingReconciliationCount: number; channelDifferenceCount: number; openShiftCount: number; reviewPendingShiftCount: number; reviewPendingShiftAmountMinor: number }
export interface BrandStoreFinancialOverview { fromDate: string; toDate: string; todayRevenueMinor: number; periodNetRevenueMinor: number; storedValueNetMinor: number; pendingReconciliationMinor: number; channelDifferenceCount: number; stores: StoreFinancialOverview[] }
export interface DashboardTrend { date: string; netRevenueMinor: number; orderCount: number; visitCount: number }
export interface DashboardPaymentMix { methodCode: string; methodName: string; amountMinor: number; allocationCount: number }
export interface DashboardStoreSnapshot { storeId: string; storeCode: string; storeName: string; todayRevenueMinor: number; monthRevenueMinor: number; lifetimeRevenueMinor: number; storedValuePrincipalBalanceMinor: number; storedValueBonusBalanceMinor: number; storedValueBalanceMinor: number; activeMemberCount: number; activeFacilityCount: number; pendingReconciliationMinor: number; pendingReconciliationCount: number; openShiftCount: number; reviewPendingShiftCount: number }
export interface DashboardOverview { scopeName: string; trendFromDate: string; trendToDate: string; todayRevenueMinor: number; monthRevenueMinor: number; lifetimeRevenueMinor: number; storedValuePrincipalBalanceMinor: number; storedValueBonusBalanceMinor: number; storedValueBalanceMinor: number; activeMemberCount: number; activeCustomerCount: number; todayVisitCount: number; todaySettledOrderCount: number; activeFacilityCount: number; pendingReconciliationMinor: number; pendingReconciliationCount: number; openShiftCount: number; reviewPendingShiftCount: number; trend: DashboardTrend[]; paymentMix: DashboardPaymentMix[]; stores: DashboardStoreSnapshot[] }
export interface InventoryBalance { productItemId: string; productCode: string; productName: string; unitName: string; trackInventory: boolean; onHandQuantity: number; reservedQuantity: number; availableQuantity: number; version: number }
export interface InventoryMovement { id: string; productItemId: string; productCode: string; productName: string; unitName: string; movementType: string; direction: string; quantity: number; onHandBefore: number; onHandAfter: number; sourceType: string; sourceId: string; sourceLineId: string; commandId: string; operatorId?: string; occurredAtUtc: string }
export interface InventoryDocumentLine { id: string; productItemId: string; productCode: string; productName: string; unitName: string; quantity: number }
export interface InventoryDocument { id: string; documentNo: string; documentType: string; reason: string; postedBy: string; postedAtUtc: string; lines: InventoryDocumentLine[] }
export interface ProductReturn { id: string; orderId: string; orderLineId: string; productItemId: string; productCode: string; productName: string; unitName: string; quantity: number; reason: string; returnedBy: string; returnedAtUtc: string }
export interface Supplier { id: string; code: string; name: string; contactName?: string; mobile?: string; settlementTerms?: string; status: string; version: number }
export interface InventoryLot { id: string; storeId: string; productItemId: string; productCode: string; productName: string; unitName: string; batchNo: string; expiresOn?: string; unitCostMinor: number; originalQuantity: number; remainingQuantity: number; sourceType: string; createdAtUtc: string }
export interface PurchaseReceiptLine { id: string; productItemId: string; productCode: string; productName: string; unitName: string; quantity: number; unitCostMinor: number; lineCostMinor: number; batchNo: string; expiresOn?: string }
export interface PurchaseReceipt { id: string; storeId: string; supplierId: string; supplierName: string; receiptNo: string; externalNo?: string; note: string; totalCostMinor: number; postedBy: string; postedAtUtc: string; lines: PurchaseReceiptLine[] }
export interface StocktakeLine { id: string; productItemId: string; productCode: string; productName: string; unitName: string; bookQuantity: number; countedQuantity: number; differenceQuantity: number }
export interface Stocktake { id: string; storeId: string; stocktakeNo: string; reason: string; requestedBy: string; frozenAtUtc: string; status: string; approvedBy?: string; postedAtUtc?: string; decisionReason?: string; version: number; lines: StocktakeLine[] }
export interface InventoryTransferLine { id: string; productItemId: string; productCode: string; productName: string; unitName: string; quantity: number }
export interface InventoryTransfer { id: string; sourceStoreId: string; destinationStoreId: string; transferNo: string; reason: string; requestedBy: string; requestedAtUtc: string; status: string; shippedBy?: string; shippedAtUtc?: string; receivedBy?: string; receivedAtUtc?: string; decisionReason?: string; version: number; lines: InventoryTransferLine[] }

export interface PlatformCurrentUser { id: string; account: string; displayName: string; mustChangePassword: boolean }
export interface MerchantRegistrationReceipt { id: string; applicationNo: string; status: string; createdAtUtc: string }
export interface MerchantRegistrationApplication { id: string; applicationNo: string; merchantName: string; storeName: string; contactName: string; maskedMobile: string; maskedEmail?: string; desiredOwnerAccount: string; note?: string; sourceIp: string; status: string; tenantId?: string; reviewReason?: string; createdAtUtc: string; reviewedAtUtc?: string; version: number }
export interface PlatformMerchant { id: string; code: string; name: string; status: string; storeCount: number; employeeCount: number; loginAccountCount: number; createdAtUtc: string; version: number }
export interface LoginSecurityEvent { id: string; scope: string; eventType: string; resultCode: string; tenantId?: string; tenantName?: string; account: string; ipAddress: string; userAgentSummary: string; traceId: string; occurredAtUtc: string }
export interface PlatformPage<T> { items: T[]; total: number; page: number; pageSize: number }
